### ISSUE TITLE
Configure does not work on Max OS X 14.6

### ISSUE THREAD

**Issue by cmayer** [xguerin/tclap#4]
./configure fails with
"checking whether we are cross compiling... configure: error: in `/Daten/Programmieren/C++/Bib/Command_Line_Parser/tclap-1.2.2':
configure: error: cannot run C++ compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details"

Which says:
"configure:2945: x86_64-apple-darwin13.4.0-clang++ -o conftest -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-st\
rong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -std=c++14 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -Wl,-pie -Wl,\
-headerpad_max_install_names -Wl,-dead_strip_dylibs conftest.cpp  >&5
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, file was built for unsupported file form\
at ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64): /Librar\
y/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
Undefined symbols for architecture x86_64:
  "_fclose", referenced from:
      _main in conftest-c1ef63.o
  "_ferror", referenced from:
      _main in conftest-c1ef63.o
  "_fopen", referenced from:
      _main in conftest-c1ef63.o
ld: symbol(s) not found for architecture x86_64
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)"

I asked myself why configure is needed anyway, since the main contribution of this project
are header files? I have not tried this yet. Still using an older version.
